export CC="gcc -std=gnu99 -std=c11"
export CFLAGS="-gdwarf-3 -std=c++11"
export CPP="gcc -E"
export CPPFLAGS="-I/usr/local/include"
export CXX="g++ -std=c++11"
export CXXCPP="g++ -E -std=c++11"
export CXXFLAGS="-gdwarf-3 -std=c++11"
export LDFLAGS="-Xlinker -rpath -Xlinker /usr/local/lib"
export LDLIBS="-L/usr/local/lib -liRRAM -lmpfr -lgmp -lm -lpthread"
